kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-powervs-block-volumesnapshot-reader-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: ibm-powervs-block-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: openshift-csi-provisioner-volumesnapshot-reader-role
  apiGroup: rbac.authorization.k8s.io
